name = "cf-workers-status-page"
workers_dev = true
account_id = ""
type = "webpack"
webpack_config = "node_modules/flareact/webpack"
compatibility_date = "2021-07-23"

[triggers]
crons = ["*/2 * * * *"]

[site]
bucket = "out"
entry-point = "./"

# uncomment and adjust following if you are not using GitHub Actions , preview_id=""
[env.production]
kv-namespaces = [{binding="cf-workers-status-page-KV_STATUS_PAGE", id="a63f95ac8ef2477b8ae99b196c67729c"}]
# zone_id="xxx"
# route="xxx"
